---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-practice
  labels:
    app: prathamesh-deploy
spec:
  template: 
    metadata: 
      name: deploy-temp
      labels:
          app: prathamesh-deploy
    spec:
      containers:
        - name: dep-containers  
          image: httpd
          ports:
            - containerPort: 80
  selector:  
    matchLabels:
      app: prathamesh-deploy
  replicas: 3
  strategy:
    type: RollingUpdate
...

---
apiVersion: v1
kind: Service
metadata:
  name: dep-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: prathamesh-deploy
