---
apiVersion: v1
kind: Pod 
metadata:
  name: prathamesh
  labels:
    app: prathamesh-app
spec: 
  containers:
  - name: devops
    image: tomcat
    ports: 
    - containerPort: 8080
...

---
apiVersion: v1 
kind: Service
metadata: 
  name: prathamesh-service
spec:
  selector:
    app: prathamesh-app
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080
  type: NodePort
...
