---
apiVersion: v1
kind: Pod 
metadata:
  name: prathamesh
  labels:
    app: prathamesh-app
spec: 
  containers:
  - name: devops
    image: httpd
    ports: 
    - containerPort: 80
...

---
apiVersion: v1 
kind: Service
metadata: 
  name: prathamesh-service
spec:
  selector:
    app: prathamesh-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
...
