---
apiVersion: v1
kind: Pod 
metadata:
  name: prathamesh
  labels:
    app: pc
spec: 
  containers:
  - name: devops
    image: httpd
    ports: 
    - containerPort: 80
  - name: devops2
    image: tomcat
    ports:
    - containerPort: 8080
...

---
apiVersion: v1 
kind: Service
metadata: 
  name: prathamesh-service
spec:
  selector:
    app: pc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: java
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort