---
apiVersion: v1
kind: ReplicationController
metadata:
 name: rc
 labels:
    app: pc
spec:
  template:
    metadata:
      labels:
        app: pc
    spec:
      containers:
       - name: devops
         image: httpd
         ports: 
          - containerPort: 80
  replicas: 4
...

---
apiVersion: v1
kind: Service
metadata: 
  name: rc-svc
spec:
  ports:
      - name: prathamesh
        protocol: TCP
        port: 80
        targetPort: 80
  selector:
    app: pc
  type: NodePort  