---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prathamesh-sts
  labels:
    app: sts
spec:
  template:
    metadata:
      name: sts-temp
      labels:
        app: sts
    spec:
      containers:
        - name: sts-container
          image: mysql
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: prathamesh
          ports:
            - continerPort: 3306
    replicas: 4
    selector: 
      matchLabels:
        app: sts
...

---
apiVersion: v1
kind: Service
metadata: sts-svc
spec:
  Ports:
    - port: 80
      protocol: TCP
      targetPort: 3306
  selctor: 
    app: sts
...
